#include <xc.inc>
 config	    FOSC = XT
 config	    WDTE = OFF
 config	    PWRTE = ON
 config	    BOREN = ON
 config	    LVP = OFF
 config	    CPD = OFF
 config	    CP = OFF
 config	    WRT = OFF
 config	    DEBUG = OFF
 PSECT resetVec, class=CODE, delta=2
 ORG 0x00
 /*
 ADCON1 = 10xx1110B
    bit0 - bit3 (10xx)
    ADFM = 1, ADCS2 = 0, onemsiz, onemsiz
    bit4 - bit7 (1110)
    PCFG3-PCFG0 = 1110 -> AN0 (RA0) Analog, geri kalan AN1-AN7(RA1, RA2, RA3, RA4, RA5, RE0, RE1, RE2) Digital
 TRISA = 00011111B
    RA0-RA4 INPUT,  RA5 OUTPUT
 TRISB = 00001111B
    RB0-RB3 INPUT, RB4-RB7 OUTPUT
 TRISC = 00000000B
    RC0-RC7 OUTPUT
 TRISD = 00000000B
    RD0-RD7 OUTPUT
 TRISE = 00000000B
    RE0-RE2 OUTPUT
 Temperature System
    Heater	DO	RC4(23)
    Cooler	DO	RC5(24)
    Temp	AI	RA0(2)
    Tach	DI	RA4(6)
 7-Segment Display
    seg a-g	DO	RD0-RD6(19, 20, 21, 22, 27, 28, 29)
    Point(dp)	DO	RD7(30)
    D1-D4	DO	RC0-RC3(15, 16, 17, 18)
 Keypad
    P1-L1-P4-L4	DI	RB0-RB3(33, 34, 35, 36)
    P5-C1-P8-C4	DO	RB4-RB7(37, 38, 39, 40)
 UART
    P2-RX		RC6(25)
    P3-TX		RC7(26)
 */
 // 4 byte variable, 2^15 - 2^-16
 CURRENT_TEMPERATURE	    EQU	    0x20
 TEMP_TEMPERATURE	    EQU	    0x24
 // 4 byte variable, rakamsal degerleri
 CURRENT_TEMPERATURE_DIGITS EQU	    0x28
 DESIRED_TEMPERATURE_DIGITS EQU	    0x30
 FAN_SPEED_DIGITS	    EQU	    0x34
 TEMP_TEMPERATURE_DIGITS    EQU	    0x38
 DESIRED_TEMPERATURE_CHECKING_DIGITS EQU 0x40
 //
 FAN_SPEED		    EQU     0x44
 ONE_SEC_COUNTER_1	    EQU     0x45
 ONE_SEC_COUNTER_2	    EQU     0x46
 S_SEGMENT_DIGIT0	    EQU	    0x50
 S_SEGMENT_DIGIT1	    EQU	    0x51
 S_SEGMENT_DIGIT2	    EQU	    0x52
 S_SEGMENT_DIGIT3	    EQU	    0x53
	    
 SLEEP_FUNCTION_VARIABLE0   EQU     0x70
 SLEEP_FUNCTION_VARIABLE1   EQU     0x71
 SLEEP_FUNCTION_VARIABLE2   EQU     0x72
 //2 byte, ADRESH ve ADRESL degerlerini tutuyor
 ADC_VALUE		    EQU	    0x73

	    
 GOTO	MAIN
MAIN:
 CALL	INIT
 CALL	TURN_HEATER_ON
 
 MOVLW	1
 MOVWF	TEMP_TEMPERATURE_DIGITS + 0
 MOVLW	2
 MOVWF	TEMP_TEMPERATURE_DIGITS + 1
 MOVLW	3
 MOVWF	TEMP_TEMPERATURE_DIGITS + 2
 MOVLW	4
 MOVWF	TEMP_TEMPERATURE_DIGITS + 3
 
 CALL	DESIRED_NUMBER_CHECKER
 GOTO	LOOP
LOOP:
 CALL	DISPLAY_CURRENT_TEMPERATURE_2_SECOND
 CALL	DISPLAY_DESIRED_TEMPERATURE_2_SECOND
 CALL	DISPLAY_FAN_SPEED_2_SECOND
 /*
 CALL	TEMPERATURE_READ
 CALL	ADC_TO_DIGITS
 CALL	DESIRED_NUMBER_OCCASIONALLY_CHECKER
 CALL	DISPLAY_CURRENT_TEMPERATURE
 */
 //CALL	DISPLAY_FAN_SPEED
 GOTO	LOOP
INIT:
    CALL SELECT_BANK1
    MOVLW   10001110B
    MOVWF   ADCON1
    MOVLW   00011111B
    MOVWF   TRISA 
    MOVLW   00001111B
    MOVWF   TRISB
    CLRF    TRISC
    CLRF    TRISD
    CLRF    TRISE
    MOVLW   0x28  
    MOVWF   OPTION_REG
    CALL    SELECT_BANK0
    CLRF    PORTA
    CLRF    PORTB
    CLRF    PORTC
    CLRF    PORTD
    CLRF    PORTE
    RETURN
SELECT_BANK0:
    BCF	    STATUS,	STATUS_RP0_POSITION
    BCF	    STATUS,	STATUS_RP1_POSITION
    RETURN
SELECT_BANK1:
    BSF	    STATUS,	STATUS_RP0_POSITION
    BCF	    STATUS,	STATUS_RP1_POSITION
    RETURN
SELECT_BANK2:
    BCF	    STATUS,	STATUS_RP0_POSITION
    BSF	    STATUS,	STATUS_RP1_POSITION
    RETURN
SELECT_BANK3:
    BSF	    STATUS,	STATUS_RP0_POSITION
    BSF	    STATUS,	STATUS_RP1_POSITION
    RETURN
SLEEP_FUNCTION:
    MOVLW   250
    MOVWF   SLEEP_FUNCTION_VARIABLE0
SLEEP_FUNCTION_LOOP:
    NOP
    DECFSZ  SLEEP_FUNCTION_VARIABLE0
    GOTO    SLEEP_FUNCTION_LOOP
    RETURN
SLEEP_FUNCTION_50_MS_CURRENT_TEMPERATURE:
    MOVLW   45
    MOVWF   SLEEP_FUNCTION_VARIABLE1
SLEEP_FUNCTION_50_LOOP_CURRENT_TEMPERATURE:
    NOP
    CALL    DISPLAY_CURRENT_TEMPERATURE
    CALL    SLEEP_FUNCTION
    DECFSZ  SLEEP_FUNCTION_VARIABLE1
    GOTO    SLEEP_FUNCTION_50_LOOP_CURRENT_TEMPERATURE
    RETURN
SLEEP_FUNCTION_50_MS_DESIRED_TEMPERATURE:
    MOVLW   45
    MOVWF   SLEEP_FUNCTION_VARIABLE1
SLEEP_FUNCTION_50_LOOP_DESIRED_TEMPERATURE:
    NOP
    CALL    DISPLAY_DESIRED_TEMPERATURE
    CALL    SLEEP_FUNCTION
    DECFSZ  SLEEP_FUNCTION_VARIABLE1
    GOTO    SLEEP_FUNCTION_50_LOOP_DESIRED_TEMPERATURE
    RETURN
SLEEP_FUNCTION_50_MS_FAN_SPEED:
    MOVLW   45
    MOVWF   SLEEP_FUNCTION_VARIABLE1
SLEEP_FUNCTION_50_LOOP_FAN_SPEED:
    NOP
    CALL    DISPLAY_FAN_SPEED
    CALL    SLEEP_FUNCTION
    DECFSZ  SLEEP_FUNCTION_VARIABLE1
    GOTO    SLEEP_FUNCTION_50_LOOP_FAN_SPEED
    RETURN
TURN_HEATER_ON:
    BSF	    PORTC,  4
    RETURN
TURN_HEATER_OFF:
    BCF	    PORTC,  4
    RETURN
TURN_COOLER_ON:
    BSF	    PORTC,  5
    RETURN
TURN_COOLER_OFF:
    BCF	    PORTC,  5
    RETURN
TEMPERATURE_READ:
 MOVLW	11000001B
 /*
 ADCS1 = 1
 ADCS0 = 1
 (Bunlar ADC'nin çalisma hiziyla ilgiliymis)
 CHS2 = 0
 CHS1 = 0
 CHS0 = 0
 (Secilen Channel, Analog portumu 0. port o yuzden CHS degerimiz 0)
 GO-DONE = 0 
 (Daha baslamasini istemiyoruz)
 U-0 = 0 
 (Unnecessary bit)
 ADON = 1
 (ADC enable ediyor)
 */
 MOVWF	ADCON0
 CALL	SLEEP_FUNCTION 
 BSF	ADCON0,	ADCON0_GO_POSITION
TEMPERATURE_READ_LOOP:
 BTFSC	ADCON0,	ADCON0_GO_POSITION
 GOTO	TEMPERATURE_READ_LOOP
 CALL	SELECT_BANK1
 MOVF	ADRESL,	W
 CALL	SELECT_BANK0
 MOVWF	ADC_VALUE+1
 MOVF	ADRESH,	W
 MOVWF	ADC_VALUE
 
 CLRF	CURRENT_TEMPERATURE + 0
 CLRF	CURRENT_TEMPERATURE + 1
 CLRF	CURRENT_TEMPERATURE + 2
 CLRF	CURRENT_TEMPERATURE + 3
 MOVF	ADC_VALUE + 0,	W
 MOVWF	CURRENT_TEMPERATURE + 0
 MOVF	ADC_VALUE + 1,  W
 MOVWF	CURRENT_TEMPERATURE + 1
 //
 BCF	STATUS,	STATUS_C_POSITION

 RRF	CURRENT_TEMPERATURE + 0
 RRF	CURRENT_TEMPERATURE + 1
 RRF	CURRENT_TEMPERATURE + 2
 RRF	CURRENT_TEMPERATURE + 3
 
 BCF	STATUS,	STATUS_C_POSITION
 //
 
 RETURN
//----------
S_SEGMENT_SELECT_0:
 BSF	PORTC,	0
 RETURN
S_SEGMENT_SELECT_1:
 BSF	PORTC,	1
 RETURN
S_SEGMENT_SELECT_2:
 BSF	PORTC,	2
 RETURN
S_SEGMENT_SELECT_3:
 BSF	PORTC,	3
 RETURN
S_SEGMENT_UNSELECT_0:
 BCF	PORTC,	0
 RETURN
S_SEGMENT_UNSELECT_1:
 BCF	PORTC,	1
 RETURN
S_SEGMENT_UNSELECT_2:
 BCF	PORTC,	2
 RETURN
S_SEGMENT_UNSELECT_3:
 BCF	PORTC,	3
 RETURN
S_SEGMENT_0:
 MOVLW	00111111B
 MOVWF	PORTD
 RETURN
S_SEGMENT_1:
 MOVLW	00000110B
 MOVWF	PORTD
 RETURN
S_SEGMENT_2:
 MOVLW   01011011B
 MOVWF   PORTD
 RETURN
S_SEGMENT_3:
 MOVLW   01001111B
 MOVWF   PORTD
 RETURN
S_SEGMENT_4:
 MOVLW   01100110B
 MOVWF   PORTD
 RETURN
S_SEGMENT_5:
 MOVLW   01101101B
 MOVWF   PORTD
 RETURN
S_SEGMENT_6:
 MOVLW   01111101B
 MOVWF   PORTD
 RETURN
S_SEGMENT_7:
 MOVLW   00000111B
 MOVWF   PORTD
 RETURN
S_SEGMENT_8:
 MOVLW   01111111B
 MOVWF   PORTD
 RETURN
S_SEGMENT_9:
 MOVLW   01101111B
 MOVWF   PORTD
 RETURN
S_SEGMENT_POINT:
 BSF	PORTD,	7
 RETURN
DIGIT_CHOOSER:
 ADDWF	PCL,	F
 GOTO	S_SEGMENT_0
 GOTO	S_SEGMENT_1
 GOTO	S_SEGMENT_2
 GOTO	S_SEGMENT_3
 GOTO	S_SEGMENT_4
 GOTO	S_SEGMENT_5
 GOTO	S_SEGMENT_6
 GOTO	S_SEGMENT_7
 GOTO	S_SEGMENT_8
 GOTO	S_SEGMENT_9
ADC_TO_DIGITS:
 CALL	SELECT_BANK0
 CLRF	CURRENT_TEMPERATURE_DIGITS + 0
 CLRF	CURRENT_TEMPERATURE_DIGITS + 1
 CLRF	CURRENT_TEMPERATURE_DIGITS + 2
 CLRF	CURRENT_TEMPERATURE_DIGITS + 3
ADC_TO_DIGITS_SUBFUNCTION_0:// 10 = 00000000 00001010 00000000 00000000
 BCF	STATUS, STATUS_C_POSITION
 MOVF	CURRENT_TEMPERATURE + 0,    W
 MOVWF	TEMP_TEMPERATURE + 0
 MOVF	CURRENT_TEMPERATURE + 1,    W
 MOVWF	TEMP_TEMPERATURE + 1 
 MOVF	CURRENT_TEMPERATURE + 2,    W
 MOVWF	TEMP_TEMPERATURE + 2
 MOVF	CURRENT_TEMPERATURE + 3,    W
 MOVWF	TEMP_TEMPERATURE + 3
 MOVLW	00000000B
 SUBWF  TEMP_TEMPERATURE + 3, F
 BTFSC  STATUS, STATUS_C_POSITION
 GOTO   ADC_TO_DIGITS_SUBFUNCTION_0_SUB_BYTE_2
 DECF   TEMP_TEMPERATURE + 2, F
 INCFSZ TEMP_TEMPERATURE + 2, W
 GOTO   ADC_TO_DIGITS_SUBFUNCTION_0_SUB_BYTE_2
 DECF   TEMP_TEMPERATURE + 1, F
 INCFSZ TEMP_TEMPERATURE + 1, W
 GOTO   ADC_TO_DIGITS_SUBFUNCTION_0_SUB_BYTE_2
 DECF   TEMP_TEMPERATURE + 0, F
ADC_TO_DIGITS_SUBFUNCTION_0_SUB_BYTE_2:
 MOVLW	00000000B
 SUBWF  TEMP_TEMPERATURE + 2, F
 BTFSC  STATUS, STATUS_C_POSITION
 GOTO   ADC_TO_DIGITS_SUBFUNCTION_0_SUB_BYTE_1
 DECF   TEMP_TEMPERATURE + 1, F
 INCFSZ TEMP_TEMPERATURE + 1, W
 GOTO   ADC_TO_DIGITS_SUBFUNCTION_0_SUB_BYTE_1
 DECF   TEMP_TEMPERATURE + 0, F
ADC_TO_DIGITS_SUBFUNCTION_0_SUB_BYTE_1:
 MOVLW	00001010B
 SUBWF  TEMP_TEMPERATURE + 1, F
 BTFSC  STATUS, STATUS_C_POSITION
 GOTO   ADC_TO_DIGITS_SUBFUNCTION_0_SUB_BYTE_0
 DECF   TEMP_TEMPERATURE + 0, F
ADC_TO_DIGITS_SUBFUNCTION_0_SUB_BYTE_0:
 MOVLW   00000000B
 SUBWF  TEMP_TEMPERATURE + 0, F
 BTFSS	TEMP_TEMPERATURE + 0,	7
 GOTO	ADC_TO_DIGITS_THOUSANDS
ADC_TO_DIGITS_SUBFUNCTION_1:// 1 = 00000000 00000001 00000000 00000000
 BCF	STATUS, STATUS_C_POSITION
 MOVF	CURRENT_TEMPERATURE + 0,    W
 MOVWF	TEMP_TEMPERATURE + 0
 MOVF	CURRENT_TEMPERATURE + 1,    W
 MOVWF	TEMP_TEMPERATURE + 1 
 MOVF	CURRENT_TEMPERATURE + 2,    W
 MOVWF	TEMP_TEMPERATURE + 2
 MOVF	CURRENT_TEMPERATURE + 3,    W
 MOVWF	TEMP_TEMPERATURE + 3
 MOVLW	00000000B
 SUBWF  TEMP_TEMPERATURE + 3, F
 BTFSC  STATUS, STATUS_C_POSITION
 GOTO   ADC_TO_DIGITS_SUBFUNCTION_1_SUB_BYTE_2
 DECF   TEMP_TEMPERATURE + 2, F
 INCFSZ TEMP_TEMPERATURE + 2, W
 GOTO   ADC_TO_DIGITS_SUBFUNCTION_1_SUB_BYTE_2
 DECF   TEMP_TEMPERATURE + 1, F
 INCFSZ TEMP_TEMPERATURE + 1, W
 GOTO   ADC_TO_DIGITS_SUBFUNCTION_1_SUB_BYTE_2
 DECF   TEMP_TEMPERATURE + 0, F
ADC_TO_DIGITS_SUBFUNCTION_1_SUB_BYTE_2:
 MOVLW	00000000B
 SUBWF  TEMP_TEMPERATURE + 2, F
 BTFSC  STATUS, STATUS_C_POSITION
 GOTO   ADC_TO_DIGITS_SUBFUNCTION_1_SUB_BYTE_1
 DECF   TEMP_TEMPERATURE + 1, F
 INCFSZ TEMP_TEMPERATURE + 1, W
 GOTO   ADC_TO_DIGITS_SUBFUNCTION_1_SUB_BYTE_1
 DECF   TEMP_TEMPERATURE + 0, F
ADC_TO_DIGITS_SUBFUNCTION_1_SUB_BYTE_1:
 MOVLW	00000001B
 SUBWF  TEMP_TEMPERATURE + 1, F
 BTFSC  STATUS, STATUS_C_POSITION
 GOTO   ADC_TO_DIGITS_SUBFUNCTION_1_SUB_BYTE_0
 DECF   TEMP_TEMPERATURE + 0, F
ADC_TO_DIGITS_SUBFUNCTION_1_SUB_BYTE_0:
 MOVLW   00000000B
 SUBWF  TEMP_TEMPERATURE + 0, F
 BTFSS	TEMP_TEMPERATURE + 0,	7
 GOTO	ADC_TO_DIGITS_HUNDREDS
ADC_TO_DIGITS_SUBFUNCTION_2:// 0.1 = 00000000 00000000 00011001 10011010
 BCF	STATUS, STATUS_C_POSITION
 MOVF	CURRENT_TEMPERATURE + 0,    W
 MOVWF	TEMP_TEMPERATURE + 0
 MOVF	CURRENT_TEMPERATURE + 1,    W
 MOVWF	TEMP_TEMPERATURE + 1 
 MOVF	CURRENT_TEMPERATURE + 2,    W
 MOVWF	TEMP_TEMPERATURE + 2
 MOVF	CURRENT_TEMPERATURE + 3,    W
 MOVWF	TEMP_TEMPERATURE + 3
 MOVLW	10011010B
 SUBWF  TEMP_TEMPERATURE + 3, F
 BTFSC  STATUS, STATUS_C_POSITION
 GOTO   ADC_TO_DIGITS_SUBFUNCTION_2_SUB_BYTE_2
 DECF   TEMP_TEMPERATURE + 2, F
 INCFSZ TEMP_TEMPERATURE + 2, W
 GOTO   ADC_TO_DIGITS_SUBFUNCTION_2_SUB_BYTE_2
 DECF   TEMP_TEMPERATURE + 1, F
 INCFSZ TEMP_TEMPERATURE + 1, W
 GOTO   ADC_TO_DIGITS_SUBFUNCTION_2_SUB_BYTE_2
 DECF   TEMP_TEMPERATURE + 0, F
ADC_TO_DIGITS_SUBFUNCTION_2_SUB_BYTE_2:
 MOVLW	00011001B
 SUBWF  TEMP_TEMPERATURE + 2, F
 BTFSC  STATUS, STATUS_C_POSITION
 GOTO   ADC_TO_DIGITS_SUBFUNCTION_2_SUB_BYTE_1
 DECF   TEMP_TEMPERATURE + 1, F
 INCFSZ TEMP_TEMPERATURE + 1, W
 GOTO   ADC_TO_DIGITS_SUBFUNCTION_2_SUB_BYTE_1
 DECF   TEMP_TEMPERATURE + 0, F
ADC_TO_DIGITS_SUBFUNCTION_2_SUB_BYTE_1:
 MOVLW	00000000B
 SUBWF  TEMP_TEMPERATURE + 1, F
 BTFSC  STATUS, STATUS_C_POSITION
 GOTO   ADC_TO_DIGITS_SUBFUNCTION_2_SUB_BYTE_0
 DECF   TEMP_TEMPERATURE + 0, F
ADC_TO_DIGITS_SUBFUNCTION_2_SUB_BYTE_0:
 MOVLW   00000000B
 SUBWF  TEMP_TEMPERATURE + 0, F
 BTFSS	TEMP_TEMPERATURE + 0,	7
 GOTO	ADC_TO_DIGITS_TENS
ADC_TO_DIGITS_SUBFUNCTION_3:// 0.01 = 00000000 00000000 00000010 10010000 
 BCF	STATUS, STATUS_C_POSITION
 MOVF	CURRENT_TEMPERATURE + 0,    W
 MOVWF	TEMP_TEMPERATURE + 0
 MOVF	CURRENT_TEMPERATURE + 1,    W
 MOVWF	TEMP_TEMPERATURE + 1 
 MOVF	CURRENT_TEMPERATURE + 2,    W
 MOVWF	TEMP_TEMPERATURE + 2
 MOVF	CURRENT_TEMPERATURE + 3,    W
 MOVWF	TEMP_TEMPERATURE + 3
 MOVLW	10010000B
 SUBWF  TEMP_TEMPERATURE + 3, F
 BTFSC  STATUS, STATUS_C_POSITION
 GOTO   ADC_TO_DIGITS_SUBFUNCTION_3_SUB_BYTE_2
 DECF   TEMP_TEMPERATURE + 2, F
 INCFSZ TEMP_TEMPERATURE + 2, W
 GOTO   ADC_TO_DIGITS_SUBFUNCTION_3_SUB_BYTE_2
 DECF   TEMP_TEMPERATURE + 1, F
 INCFSZ TEMP_TEMPERATURE + 1, W
 GOTO   ADC_TO_DIGITS_SUBFUNCTION_3_SUB_BYTE_2
 DECF   TEMP_TEMPERATURE + 0, F
ADC_TO_DIGITS_SUBFUNCTION_3_SUB_BYTE_2:
 MOVLW	00000010B
 SUBWF  TEMP_TEMPERATURE + 2, F
 BTFSC  STATUS, STATUS_C_POSITION
 GOTO   ADC_TO_DIGITS_SUBFUNCTION_3_SUB_BYTE_1
 DECF   TEMP_TEMPERATURE + 1, F
 INCFSZ TEMP_TEMPERATURE + 1, W
 GOTO   ADC_TO_DIGITS_SUBFUNCTION_3_SUB_BYTE_1
 DECF   TEMP_TEMPERATURE + 0, F
ADC_TO_DIGITS_SUBFUNCTION_3_SUB_BYTE_1:
 MOVLW	00000000B
 SUBWF  TEMP_TEMPERATURE + 1, F
 BTFSC  STATUS, STATUS_C_POSITION
 GOTO   ADC_TO_DIGITS_SUBFUNCTION_3_SUB_BYTE_0
 DECF   TEMP_TEMPERATURE + 0, F
ADC_TO_DIGITS_SUBFUNCTION_3_SUB_BYTE_0:
 MOVLW   00000000B
 SUBWF  TEMP_TEMPERATURE + 0, F
 BTFSS	TEMP_TEMPERATURE + 0,	7
 GOTO	ADC_TO_DIGITS_ONES
 RETURN
ADC_TO_DIGITS_THOUSANDS:// 10 = 00000000 00001010 00000000 00000000
 BCF	STATUS, STATUS_C_POSITION
 INCF	CURRENT_TEMPERATURE_DIGITS + 0, F
 MOVLW	00000000B
 SUBWF  CURRENT_TEMPERATURE + 3, F
 BTFSC  STATUS, STATUS_C_POSITION
 GOTO   ADC_TO_DIGITS_THOUSANDS_SUB_BYTE_2
 DECF   CURRENT_TEMPERATURE + 2, F
 INCFSZ CURRENT_TEMPERATURE + 2, W
 GOTO   ADC_TO_DIGITS_THOUSANDS_SUB_BYTE_2
 DECF   CURRENT_TEMPERATURE + 1, F
 INCFSZ CURRENT_TEMPERATURE + 1, W
 GOTO   ADC_TO_DIGITS_THOUSANDS_SUB_BYTE_2
 DECF   CURRENT_TEMPERATURE + 0, F
ADC_TO_DIGITS_THOUSANDS_SUB_BYTE_2:
 MOVLW	00000000B
 SUBWF  CURRENT_TEMPERATURE + 2, F
 BTFSC  STATUS, STATUS_C_POSITION
 GOTO   ADC_TO_DIGITS_THOUSANDS_SUB_BYTE_1
 DECF   CURRENT_TEMPERATURE + 1, F
 INCFSZ CURRENT_TEMPERATURE + 1, W
 GOTO   ADC_TO_DIGITS_THOUSANDS_SUB_BYTE_1
 DECF   CURRENT_TEMPERATURE + 0, F
ADC_TO_DIGITS_THOUSANDS_SUB_BYTE_1:
 MOVLW	00001010B
 SUBWF  CURRENT_TEMPERATURE + 1, F
 BTFSC  STATUS, STATUS_C_POSITION
 GOTO   ADC_TO_DIGITS_THOUSANDS_SUB_BYTE_0
 DECF   CURRENT_TEMPERATURE + 0, F
ADC_TO_DIGITS_THOUSANDS_SUB_BYTE_0:
 MOVLW   00000000B
 SUBWF  CURRENT_TEMPERATURE + 0,    F
 GOTO	ADC_TO_DIGITS_SUBFUNCTION_0
ADC_TO_DIGITS_HUNDREDS:// 1 = 00000000 00000001 00000000 00000000
 BCF	STATUS, STATUS_C_POSITION
 INCF	CURRENT_TEMPERATURE_DIGITS + 1, F
 MOVLW	00000000B
 SUBWF  CURRENT_TEMPERATURE + 3, F
 BTFSC  STATUS, STATUS_C_POSITION
 GOTO   ADC_TO_DIGITS_HUNDREDS_SUB_BYTE_2
 DECF   CURRENT_TEMPERATURE + 2, F
 INCFSZ CURRENT_TEMPERATURE + 2, W
 GOTO   ADC_TO_DIGITS_HUNDREDS_SUB_BYTE_2
 DECF   CURRENT_TEMPERATURE + 1, F
 INCFSZ CURRENT_TEMPERATURE + 1, W
 GOTO   ADC_TO_DIGITS_HUNDREDS_SUB_BYTE_2
 DECF   CURRENT_TEMPERATURE + 0, F
ADC_TO_DIGITS_HUNDREDS_SUB_BYTE_2:
 MOVLW	00000000B
 SUBWF  CURRENT_TEMPERATURE + 2, F
 BTFSC  STATUS, STATUS_C_POSITION
 GOTO   ADC_TO_DIGITS_HUNDREDS_SUB_BYTE_1
 DECF   CURRENT_TEMPERATURE + 1, F
 INCFSZ CURRENT_TEMPERATURE + 1, W
 GOTO   ADC_TO_DIGITS_HUNDREDS_SUB_BYTE_1
 DECF   CURRENT_TEMPERATURE + 0, F
ADC_TO_DIGITS_HUNDREDS_SUB_BYTE_1:
 MOVLW	00000001B
 SUBWF  CURRENT_TEMPERATURE + 1, F
 BTFSC  STATUS, STATUS_C_POSITION
 GOTO   ADC_TO_DIGITS_HUNDREDS_SUB_BYTE_0
 DECF   CURRENT_TEMPERATURE + 0, F
ADC_TO_DIGITS_HUNDREDS_SUB_BYTE_0:
 MOVLW   00000000B
 SUBWF  CURRENT_TEMPERATURE + 0,    F
 GOTO	ADC_TO_DIGITS_SUBFUNCTION_1
ADC_TO_DIGITS_TENS:// 0.1 = 00000000 00000000 00011001 10011010
 BCF	STATUS, STATUS_C_POSITION
 INCF	CURRENT_TEMPERATURE_DIGITS + 2, F
 MOVLW	10011010B
 SUBWF  CURRENT_TEMPERATURE + 3, F
 BTFSC  STATUS, STATUS_C_POSITION
 GOTO   ADC_TO_DIGITS_TENS_SUB_BYTE_2
 DECF   CURRENT_TEMPERATURE + 2, F
 INCFSZ CURRENT_TEMPERATURE + 2, W
 GOTO   ADC_TO_DIGITS_TENS_SUB_BYTE_2
 DECF   CURRENT_TEMPERATURE + 1, F
 INCFSZ CURRENT_TEMPERATURE + 1, W
 GOTO   ADC_TO_DIGITS_TENS_SUB_BYTE_2
 DECF   CURRENT_TEMPERATURE + 0, F
ADC_TO_DIGITS_TENS_SUB_BYTE_2:
 MOVLW	00011001B
 SUBWF  CURRENT_TEMPERATURE + 2, F
 BTFSC  STATUS, STATUS_C_POSITION
 GOTO   ADC_TO_DIGITS_TENS_SUB_BYTE_1
 DECF   CURRENT_TEMPERATURE + 1, F
 INCFSZ CURRENT_TEMPERATURE + 1, W
 GOTO   ADC_TO_DIGITS_TENS_SUB_BYTE_1
 DECF   CURRENT_TEMPERATURE + 0, F
ADC_TO_DIGITS_TENS_SUB_BYTE_1:
 MOVLW	00000000B
 SUBWF  CURRENT_TEMPERATURE + 1, F
 BTFSC  STATUS, STATUS_C_POSITION
 GOTO   ADC_TO_DIGITS_TENS_SUB_BYTE_0
 DECF   CURRENT_TEMPERATURE + 0, F
ADC_TO_DIGITS_TENS_SUB_BYTE_0:
 MOVLW   00000000B
 SUBWF  CURRENT_TEMPERATURE + 0, F
 GOTO ADC_TO_DIGITS_SUBFUNCTION_2
ADC_TO_DIGITS_ONES:// 0.01 = 00000000 00000000 00000010 10010000
 BCF	STATUS, STATUS_C_POSITION
 INCF	CURRENT_TEMPERATURE_DIGITS + 3, F
 MOVLW	10010000B
 SUBWF  CURRENT_TEMPERATURE + 3, F
 BTFSC  STATUS, STATUS_C_POSITION
 GOTO   ADC_TO_DIGITS_ONES_SUB_BYTE_2
 DECF   CURRENT_TEMPERATURE + 2, F
 INCFSZ CURRENT_TEMPERATURE + 2, W
 GOTO   ADC_TO_DIGITS_ONES_SUB_BYTE_2
 DECF   CURRENT_TEMPERATURE + 1, F
 INCFSZ CURRENT_TEMPERATURE + 1, W
 GOTO   ADC_TO_DIGITS_ONES_SUB_BYTE_2
 DECF   CURRENT_TEMPERATURE + 0, F
ADC_TO_DIGITS_ONES_SUB_BYTE_2:
 MOVLW	00000010B
 SUBWF  CURRENT_TEMPERATURE + 2, F
 BTFSC  STATUS, STATUS_C_POSITION
 GOTO   ADC_TO_DIGITS_ONES_SUB_BYTE_1
 DECF   CURRENT_TEMPERATURE + 1, F
 INCFSZ CURRENT_TEMPERATURE + 1, W
 GOTO   ADC_TO_DIGITS_ONES_SUB_BYTE_1
 DECF   CURRENT_TEMPERATURE + 0, F
ADC_TO_DIGITS_ONES_SUB_BYTE_1:
 MOVLW	00000000B
 SUBWF  CURRENT_TEMPERATURE + 1, F
 BTFSC  STATUS, STATUS_C_POSITION
 GOTO   ADC_TO_DIGITS_ONES_SUB_BYTE_0
 DECF   CURRENT_TEMPERATURE + 0, F
ADC_TO_DIGITS_ONES_SUB_BYTE_0:
 MOVLW	00000000B
 SUBWF  CURRENT_TEMPERATURE + 0, F
 GOTO	ADC_TO_DIGITS_SUBFUNCTION_3
FAN_SPEED_TO_DIGITS:
 CALL        SELECT_BANK0
 CALL SELECT_BANK0
 CLRF        FAN_SPEED_DIGITS + 0
 CLRF FAN_SPEED_DIGITS + 0
 CLRF        FAN_SPEED_DIGITS + 1
 CLRF FAN_SPEED_DIGITS + 1
 CLRF        FAN_SPEED_DIGITS + 2
 CLRF FAN_SPEED_DIGITS + 2
 CLRF        FAN_SPEED_DIGITS + 3
 CLRF FAN_SPEED_DIGITS + 3
FAN_SPEED_TO_DIGIT_SUBFUNCTION_0:
FAN_SPEED_TO_DIGITS_SUBFUNCTION_0:
 MOVLW 01100100B
 SUBWF FAN_SPEED, W
 BTFSC STATUS, STATUS_C_POSITION
 GOTO FAN_SPEED_TO_DIGITS_HUNDREDS
FAN_SPEED_TO_DIGITS_SUBFUNCTION_1:
 MOVLW 00001010B
 SUBWF FAN_SPEED, W
 BTFSC STATUS, STATUS_C_POSITION
 GOTO FAN_SPEED_TO_DIGITS_TENS
 MOVF FAN_SPEED, W
 MOVWF FAN_SPEED_DIGITS + 3
 RETURN
FAN_SPEED_TO_DIGITS_HUNDREDS:
 INCF FAN_SPEED_DIGITS + 1
 MOVLW 01100100B
 SUBWF FAN_SPEED, F
 GOTO FAN_SPEED_TO_DIGITS_SUBFUNCTION_0
FAN_SPEED_TO_DIGITS_TENS:
 INCF FAN_SPEED_DIGITS + 2
 MOVLW 00001010B
 SUBWF FAN_SPEED, F
 GOTO FAN_SPEED_TO_DIGITS_SUBFUNCTION_1
DISPLAY_CURRENT_TEMPERATURE:
 CALL	S_SEGMENT_SELECT_0
 MOVLW  HIGH DIGIT_CHOOSER
 MOVWF  PCLATH
 MOVF	CURRENT_TEMPERATURE_DIGITS + 0, W
 CALL	DIGIT_CHOOSER
 CALL	SLEEP_FUNCTION
 CALL	S_SEGMENT_UNSELECT_0
 CALL	S_SEGMENT_SELECT_1
 MOVLW  HIGH DIGIT_CHOOSER
 MOVWF  PCLATH
 MOVF	CURRENT_TEMPERATURE_DIGITS + 1, W
 CALL	DIGIT_CHOOSER
 CALL	S_SEGMENT_POINT
 CALL	SLEEP_FUNCTION
 CALL	S_SEGMENT_UNSELECT_1
 CALL	S_SEGMENT_SELECT_2
 MOVLW  HIGH DIGIT_CHOOSER
 MOVWF  PCLATH
 MOVF	CURRENT_TEMPERATURE_DIGITS + 2, W
 CALL	DIGIT_CHOOSER
 CALL	SLEEP_FUNCTION
 CALL	S_SEGMENT_UNSELECT_2
 CALL	S_SEGMENT_SELECT_3
 MOVLW  HIGH DIGIT_CHOOSER
 MOVWF  PCLATH
 MOVF	CURRENT_TEMPERATURE_DIGITS + 3, W
 CALL	DIGIT_CHOOSER
 CALL	SLEEP_FUNCTION
 CALL	S_SEGMENT_UNSELECT_3
 RETURN
DISPLAY_DESIRED_TEMPERATURE:
 CALL	S_SEGMENT_SELECT_0
 MOVLW  HIGH DIGIT_CHOOSER
 MOVWF  PCLATH
 MOVF	DESIRED_TEMPERATURE_DIGITS + 0, W
 CALL	DIGIT_CHOOSER
 CALL	SLEEP_FUNCTION
 CALL	S_SEGMENT_UNSELECT_0
 CALL	S_SEGMENT_SELECT_1
 MOVLW  HIGH DIGIT_CHOOSER
 MOVWF  PCLATH
 MOVF	DESIRED_TEMPERATURE_DIGITS + 1, W
 CALL	DIGIT_CHOOSER
 CALL	S_SEGMENT_POINT
 CALL	SLEEP_FUNCTION
 CALL	S_SEGMENT_UNSELECT_1
 CALL	S_SEGMENT_SELECT_2
 MOVLW  HIGH DIGIT_CHOOSER
 MOVWF  PCLATH
 MOVF	DESIRED_TEMPERATURE_DIGITS + 2, W
 CALL	DIGIT_CHOOSER
 CALL	SLEEP_FUNCTION
 CALL	S_SEGMENT_UNSELECT_2
 CALL	S_SEGMENT_SELECT_3
 MOVLW  HIGH DIGIT_CHOOSER
 MOVWF  PCLATH
 MOVF	DESIRED_TEMPERATURE_DIGITS + 3, W
 CALL	DIGIT_CHOOSER
 CALL	SLEEP_FUNCTION
 CALL	S_SEGMENT_UNSELECT_3
 RETURN
DISPLAY_FAN_SPEED:
 CALL	S_SEGMENT_SELECT_0
 MOVLW  HIGH DIGIT_CHOOSER
 MOVWF  PCLATH
 MOVF	FAN_SPEED_DIGITS + 0, W
 CALL	DIGIT_CHOOSER
 CALL	SLEEP_FUNCTION
 CALL	S_SEGMENT_UNSELECT_0
 CALL	S_SEGMENT_SELECT_1
 MOVLW  HIGH DIGIT_CHOOSER
 MOVWF  PCLATH
 MOVF	FAN_SPEED_DIGITS + 1, W
 CALL	DIGIT_CHOOSER
 CALL	SLEEP_FUNCTION
 CALL	S_SEGMENT_UNSELECT_1
 CALL	S_SEGMENT_SELECT_2
 MOVLW  HIGH DIGIT_CHOOSER
 MOVWF  PCLATH
 MOVF	FAN_SPEED_DIGITS + 2, W
 CALL	DIGIT_CHOOSER
 CALL	SLEEP_FUNCTION
 CALL	S_SEGMENT_UNSELECT_2
 CALL	S_SEGMENT_SELECT_3
 MOVLW  HIGH DIGIT_CHOOSER
 MOVWF  PCLATH
 MOVF	FAN_SPEED_DIGITS + 3, W
 CALL	DIGIT_CHOOSER
 CALL	SLEEP_FUNCTION
 CALL	S_SEGMENT_UNSELECT_3
 RETURN
DESIRED_NUMBER_CHECKER:
 MOVLW	5
 MOVWF	DESIRED_TEMPERATURE_CHECKING_DIGITS + 0
 MOVLW	0
 MOVWF	DESIRED_TEMPERATURE_CHECKING_DIGITS + 1
 MOVLW	0
 MOVWF	DESIRED_TEMPERATURE_CHECKING_DIGITS + 2
 MOVLW	0
 MOVWF	DESIRED_TEMPERATURE_CHECKING_DIGITS + 3
 MOVF	TEMP_TEMPERATURE_DIGITS + 0,	W
 SUBWF	DESIRED_TEMPERATURE_CHECKING_DIGITS + 0,    W
 BTFSS	STATUS,	    STATUS_C_POSITION
 RETURN
 BTFSS	STATUS,	    STATUS_Z_POSITION
 GOTO	DESIRED_NUMBER_CHECKER_PART_2
 MOVF	TEMP_TEMPERATURE_DIGITS + 1,	W
 SUBWF	DESIRED_TEMPERATURE_CHECKING_DIGITS + 1,    W
 BTFSS	STATUS,	    STATUS_C_POSITION
 RETURN
 BTFSS	STATUS,	    STATUS_Z_POSITION
 GOTO	DESIRED_NUMBER_CHECKER_PART_2
 MOVF	TEMP_TEMPERATURE_DIGITS + 2,	W
 SUBWF	DESIRED_TEMPERATURE_CHECKING_DIGITS + 2,    W
 BTFSS	STATUS,	    STATUS_C_POSITION
 RETURN
 BTFSS	STATUS,	    STATUS_Z_POSITION
 GOTO	DESIRED_NUMBER_CHECKER_PART_2
 MOVF	TEMP_TEMPERATURE_DIGITS + 3,	W
 SUBWF	DESIRED_TEMPERATURE_CHECKING_DIGITS + 3,    W
 BTFSS	STATUS,	    STATUS_C_POSITION
 RETURN
DESIRED_NUMBER_CHECKER_PART_2:
 MOVLW	1
 MOVWF	DESIRED_TEMPERATURE_CHECKING_DIGITS + 0
 MOVLW	0
 MOVWF	DESIRED_TEMPERATURE_CHECKING_DIGITS + 1
 MOVLW	0
 MOVWF	DESIRED_TEMPERATURE_CHECKING_DIGITS + 2
 MOVLW	0
 MOVWF	DESIRED_TEMPERATURE_CHECKING_DIGITS + 3
 MOVF	DESIRED_TEMPERATURE_CHECKING_DIGITS + 0,    W
 SUBWF	TEMP_TEMPERATURE_DIGITS + 0,	W
 BTFSS	STATUS,	    STATUS_C_POSITION
 RETURN
 BTFSS	STATUS,	    STATUS_Z_POSITION
 GOTO	DESIRED_NUMBER_CHECKER_PART_3
 MOVF	DESIRED_TEMPERATURE_CHECKING_DIGITS + 1,    W
 SUBWF	TEMP_TEMPERATURE_DIGITS + 1,	W
 BTFSS	STATUS,	    STATUS_C_POSITION
 RETURN
 BTFSS	STATUS,	    STATUS_Z_POSITION
 GOTO	DESIRED_NUMBER_CHECKER_PART_3
 MOVF	DESIRED_TEMPERATURE_CHECKING_DIGITS + 2,    W
 SUBWF	TEMP_TEMPERATURE_DIGITS + 2,	W
 BTFSS	STATUS,	    STATUS_C_POSITION
 RETURN
 BTFSS	STATUS,	    STATUS_Z_POSITION
 GOTO	DESIRED_NUMBER_CHECKER_PART_3
 MOVF	DESIRED_TEMPERATURE_CHECKING_DIGITS + 3,    W
 SUBWF	TEMP_TEMPERATURE_DIGITS + 3,	W
 BTFSS	STATUS,	    STATUS_C_POSITION
 RETURN
DESIRED_NUMBER_CHECKER_PART_3:
 MOVF	TEMP_TEMPERATURE_DIGITS + 0,	W
 MOVWF	DESIRED_TEMPERATURE_DIGITS + 0
 MOVF	TEMP_TEMPERATURE_DIGITS + 1,	W
 MOVWF	DESIRED_TEMPERATURE_DIGITS + 1
 MOVF	TEMP_TEMPERATURE_DIGITS + 2,	W
 MOVWF	DESIRED_TEMPERATURE_DIGITS + 2
 MOVF	TEMP_TEMPERATURE_DIGITS + 3,	W
 MOVWF	DESIRED_TEMPERATURE_DIGITS + 3
 RETURN
DESIRED_NUMBER_OCCASIONALLY_CHECKER:
 MOVF	DESIRED_TEMPERATURE_DIGITS + 0, W
 SUBWF	CURRENT_TEMPERATURE_DIGITS + 0,	W
 BTFSS	STATUS,	    STATUS_C_POSITION
 GOTO	START_HEATING
 BTFSS	STATUS,	    STATUS_Z_POSITION
 GOTO	DESIRED_NUMBER_OCCASIONALLY_CHECKER_PART_2
 MOVF	DESIRED_TEMPERATURE_DIGITS + 1, W
 SUBWF	CURRENT_TEMPERATURE_DIGITS + 1,	W
 BTFSS	STATUS,	    STATUS_C_POSITION
 GOTO	START_HEATING
 BTFSS	STATUS,	    STATUS_Z_POSITION
 GOTO	DESIRED_NUMBER_OCCASIONALLY_CHECKER_PART_2
 MOVF	DESIRED_TEMPERATURE_DIGITS + 2, W
 SUBWF	CURRENT_TEMPERATURE_DIGITS + 2,	W
 BTFSS	STATUS,	    STATUS_C_POSITION
 GOTO	START_HEATING
 BTFSS	STATUS,	    STATUS_Z_POSITION
 GOTO	DESIRED_NUMBER_OCCASIONALLY_CHECKER_PART_2
 MOVF	DESIRED_TEMPERATURE_DIGITS + 3,	W
 SUBWF	CURRENT_TEMPERATURE_DIGITS + 3,	W
 BTFSS	STATUS,	    STATUS_C_POSITION
 GOTO	START_HEATING
 BTFSS	STATUS,	    STATUS_Z_POSITION
 GOTO	STOP_HEATING_AND_COOLING
DESIRED_NUMBER_OCCASIONALLY_CHECKER_PART_2:
START_COOLING:
 CALL	TURN_HEATER_OFF
 CALL	TURN_COOLER_ON
 RETURN
START_HEATING:
 CALL	TURN_HEATER_ON
 CALL	TURN_COOLER_OFF
 RETURN
STOP_HEATING_AND_COOLING:
 CALL	TURN_HEATER_OFF
 CALL	TURN_COOLER_OFF
 RETURN 
DISPLAY_CURRENT_TEMPERATURE_2_SECOND:
    MOVLW   15
    MOVWF   SLEEP_FUNCTION_VARIABLE2
DISPLAY_CURRENT_TEMPERATURE_2_SECOND_LOOP:
    CLRF    TMR0
    CALL    TEMPERATURE_READ
    CALL    ADC_TO_DIGITS
    CALL    DESIRED_NUMBER_OCCASIONALLY_CHECKER
    CALL    SLEEP_FUNCTION_50_MS_CURRENT_TEMPERATURE
    CALL    DISPLAY_CURRENT_TEMPERATURE
    DECFSZ  SLEEP_FUNCTION_VARIABLE2
    GOTO    DISPLAY_CURRENT_TEMPERATURE_2_SECOND_LOOP  
    RETURN
DISPLAY_DESIRED_TEMPERATURE_2_SECOND:
    MOVLW   15
    MOVWF   SLEEP_FUNCTION_VARIABLE2
DISPLAY_DESIRED_TEMPERATURE_2_SECOND_LOOP:
    CLRF    TMR0
    CALL    TEMPERATURE_READ
    CALL    ADC_TO_DIGITS
    CALL    DESIRED_NUMBER_OCCASIONALLY_CHECKER
    CALL    SLEEP_FUNCTION_50_MS_DESIRED_TEMPERATURE
    CALL    DISPLAY_DESIRED_TEMPERATURE
    DECFSZ  SLEEP_FUNCTION_VARIABLE2
    GOTO    DISPLAY_DESIRED_TEMPERATURE_2_SECOND_LOOP  
    RETURN
DISPLAY_FAN_SPEED_2_SECOND:
    MOVLW   15
    MOVWF   SLEEP_FUNCTION_VARIABLE2
DISPLAY_FAN_SPEED_2_SECOND_LOOP:
    CLRF    TMR0
    CALL    TEMPERATURE_READ
    CALL    ADC_TO_DIGITS
    CALL    DESIRED_NUMBER_OCCASIONALLY_CHECKER
    CALL    SLEEP_FUNCTION_50_MS_FAN_SPEED
    MOVF    TMR0,   W
    MOVWF   FAN_SPEED
    CALL    FAN_SPEED_TO_DIGITS
    CALL    DISPLAY_FAN_SPEED
    DECFSZ  SLEEP_FUNCTION_VARIABLE2
    GOTO    DISPLAY_FAN_SPEED_2_SECOND_LOOP  
    RETURN